name: Autograde

on:
  push:
  pull_request:

jobs:
  test:
    name: test${{ matrix.id }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 1
          - id: 2
          - id: 3
          - id: 4
          - id: 5
          - id: 6
          - id: 7
          - id: 8
          - id: 9
          - id: 10
          - id: 11

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Run tests (week ${{ matrix.id }})
        run: |
          uv run python -m pytest -v exercises/week$(printf "%02d" ${{ matrix.id }})/test_week$(printf "%02d" ${{ matrix.id }}).py

  grade:
    name: Score
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Compute score
        continue-on-error: true
        run: |
          uv run python grade.py --verbose